### ISSUE TITLE
Settlement Workers - Prepare Worker

### ISSUE THREAD

**Issue by husobee** [brave-intl/bat-go#1178]
Each element in the prepare redis stream will result in a prepare HTTP call to the payment service running in the enclave

**Comment by evq** [comment]
Under security review: https://github.com/brave/security/issues/846

**Comment by evq** [comment]
This should already be implemented

**Comment by evq** [comment]
We will need to adjust this logic to poll for new redis prepare streams created by the prepare CLI command:
https://github.com/brave-intl/bat-go/issues/1729

**Comment by evq** [comment]
As pointed out by @clD11 instead of polling it may be better to have the prepare command to instead notify the worker about the new redis stream.  We can have a redis stream of other streams (config stream) for this purpose.

**Comment by evq** [comment]
The generic consumer completion function will absorb the behavior previously defined in https://github.com/brave-intl/bat-go/issues/1179
