### ISSUE TITLE
Settlement Workers - Submit Worker

### ISSUE THREAD

**Issue by husobee** [brave-intl/bat-go#1180]
The submit worker will start when triggered off the config stream by the authorize command. It will behave according to https://github.com/brave-intl/bat-go/issues/1746 with respect to generic processing.

For each message and retry it will call the [submit endpoint on the nitro enclave service.](https://github.com/brave-intl/bat-go/issues/1751)

The custom completion handler will ( run when submit messages -> 0 ):
- Update the s3 object to indicate payout is complete for custodians
Send an email to the operators that payout is completed
- Upload Stubs to grants claims table

**Comment by evq** [comment]
Under security review: https://github.com/brave/security/issues/846
