### ISSUE TITLE
Settlement Workers - Status Worker

### ISSUE THREAD

**Issue by husobee** [brave-intl/bat-go#1181]
Some custodians have batched settlement jobs on a particular schedule, and status checks of the transaction need to be done after a period of time.  This status worker will take transactions from consuming the `status` stream, and poll the custodian for the status of the transaction.  If the status is pending, the transaction is re-produced to the `status` stream for re-polling.  If the status is `completed` the processing is done.  If the status is `errored` the transaction is produced to an `erred` stream for reprocessing or manual intervention.

**Comment by evq** [comment]
Under security review: https://github.com/brave/security/issues/846

**Comment by evq** [comment]
closing as this is no longer needed
