### ISSUE TITLE
Settlement Workers - Error Retry Worker

### ISSUE THREAD

**Issue by husobee** [brave-intl/bat-go#1182]
Business criteria for retrying failed transactions needs to be created.

Sometimes there are errors which can be retried.  If the reason/status of the failed transaction consumed from the `erred` stream is retriable the error retry worker will produce the transaction again to the `drain` stream for retry.  

Care must be taken around the transaction idempotency key.  If the failure is codified, you will always get back that codified error with the same idempotency key.

**Comment by evq** [comment]
Under security review: https://github.com/brave/security/issues/846

**Comment by evq** [comment]
This has been redesigned and split between the new custodial submit state machines and generic consumer logic.
