### ISSUE TITLE
Settlement Enclave: Nitro Shim Utilities

### ISSUE THREAD

**Issue by husobee** [brave-intl/bat-go#1184]
rebase - https://github.com/brave-intl/bat-go/pull/836

aux nitro utils implemented from before:
incoming and outgoing proxies
AWS client that dials through proxy
log writer we can pass to zerolog
log server to receive said logs

Need to restructure the command structure to add a nitro-shim entry point, and include all the utils in the app image for deploy

**Comment by evq** [comment]
In security review: https://github.com/brave/security/issues/837
