### ISSUE TITLE
Error: Device limit reached

### ISSUE THREAD

**Issue by spitrip82** [brave-intl/bat-go#1204]
Error: Device limit reached
Your wallet cannot be verified because you've reached the maximum verified device limit.

I no longer have access to my old devices how can I solve this problem and verified my wallet? 
![Captura de ecrã 2022-02-09 004815 brave](https://user-images.githubusercontent.com/76714275/153102186-72f645cd-b058-41f1-a355-8eb91505441a.png)
Thank you in advance for your help

**Comment by Miyayes** [comment]
Hi, are you trying with Uphold? In any case, we won't be able to help you over Github as it is not a support forum. You can email me at christopher@brave.com to follow up. Thanks.
