### ISSUE TITLE
Add GET /coins/images/* coingecko proxy endpoint

### ISSUE THREAD

**Issue by nvonpentz** [brave-intl/bat-go#1424]
And replace the URLs included in the "image" field of coin market responses with our own URLs.

Details [here](https://github.com/brave/brave-core/pull/12510/files#r865796636).

**Comment by kdenhartog** [comment]
I think this issue has been addressed by https://github.com/brave/devops/issues/7563

**Comment by nvonpentz** [comment]
Yessir
