### ISSUE TITLE
unable to get time limited v2 creds for same order on different machines

### ISSUE THREAD

**Issue by LaurenWags** [brave-intl/bat-go#1697]
See https://bravesoftware.slack.com/archives/CHGKGMHDJ/p1668708106632519?thread_ts=1668617376.927489&cid=CHGKGMHDJ.

Generally:
1. On machine A, use a fresh profile and fresh email to purchase VPN from account.bravesoftware.com
2. Confirm you get credentials and are able to install/launch VPN.
3. Go to machine B
4. Again, use a fresh profile, but try to login to account.bravesoftware.com with the email from step 1.
5. After clicking on the login link from email, account.bravesoftware.com just shows spinning triangle and you are never successful.

cc @husobee

**Comment by LaurenWags** [comment]
cc @mattmcalister for visibility

**Comment by husobee** [comment]
https://github.com/brave-intl/bat-go/pull/1648 this PR includes fixes which are going to dev for developer testing now.

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue in `Windows 10 x64 - 1.46.117`

**Comment by stephendonner** [comment]
> #1648 this PR includes fixes which are going to dev for developer testing now.

@husobee I thought we had everything merged into `master`, and up in staging; is this a new dependency we'll need?

**Comment by husobee** [comment]
> > #1648 this PR includes fixes which are going to dev for developer testing now.
> 
> @husobee I thought we had everything merged into `master`, and up in staging; is this a new dependency we'll need?

@stephendonner : this feature branch is what is in staging, I need a final security review sign off before merging to master branch.  I will push the latest commits to staging which enable to multiple device credential download support.
