### ISSUE TITLE
Extend credential/token-expiration time to 30 days + 2 days

### ISSUE THREAD

**Issue by stephendonner** [brave-intl/bat-go#1707]
Summary: Extend credential/token-expiration time to 30 days + 2 days

Steps to Reproduce:
1. install `1.46.134`
2. launch Brave
3. enable `brave://flags/#brave-vpn`
4. click `Relaunch`
5. load `https://account.bravesoftware.com/`
6. enter basic-auth creds from 1Password
7. enter a unique email like `dec502@mailinator.com`
8. click on the `Log in to Brave` button in the resulting email
9. click on `Browse plans`
10. click on `Buy now` under `Brave VPN Subscription`
11. complete the Stripe checkout
12. return and cancel the plan

Right now, we give the user 1 additional overlap/grace day.

Per @mattmcalister we want to be a little more lenient and bump this up to `2` days

/cc @mattmcalister @husobee @brave-intl/qa-team @rebron @evq

**Comment by stephendonner** [comment]
Or `31 days` + `1`, as the other split we discussed in the meeting, right @evq ?

**Comment by husobee** [comment]
https://github.com/brave-intl/bat-go/pull/1648/commits/e18ae522facbb0c858144d1330b9bcc08f46f31a included here
