### ISSUE TITLE
Settlement CLI: Prepare command

### ISSUE THREAD

**Issue by evq** [brave-intl/bat-go#1729]
Primary settlement operator runs the prepare command:
- It will create a new prepare redis stream for this payout
- The prepare command will directly connect to redis put each of the transactions in the report into the prepare redis stream

**Comment by evq** [comment]
We will also have this command create a new entry in the settlements redis stream - for purposes of notifying the prepare worker about the new settlement specific prepare stream.

**Comment by husobee** [comment]
https://github.com/brave-intl/bat-go/pull/1752 ready for security review.
