### ISSUE TITLE
Settlement Enclave: Ensure HTTP responses include advised retry-after

### ISSUE THREAD

**Issue by evq** [brave-intl/bat-go#1862]

**Comment by clD11** [comment]
Protocol has been reviewed and needs to be added to the submit endpoint. Once this is done we can test it and this ticket can be closed.

For NP errors and where the payment service has been successfully reached we will return -
```
HTTP Status 202 
Header = x-submit-retry-after <delay-seconds>
```

NP errors, that maybe returned prior to the advised retry after logic above  will be retried by the http client retry policy and are distinct from NP/permanent payment service errors. Initial set is defined as -
```
408 Request Timeout
425 Too Early
429 Too Many Requests
500 Internal Server Error
502 Bad Gateway
503 Service Unavailable
504 Gateway Timeout
```
