### ISSUE TITLE
Investigate Potential Issues With Multiple Items in Order

### ISSUE THREAD

**Issue by husobee** [brave-intl/bat-go#1869]
## Order Location vs Item Location
- [x] **Handler**
    - [x] `SetOrderTrialDays` -> `ValidateOrderMerchantAndCaveats`
    - [x] `CancelOrder`       -> `ValidateOrderMerchantAndCaveats`
    - [x] `DeleteOrderCreds`  -> `ValidateOrderMerchantAndCaveats`
- [x] **Service**
    - [x] `ValidateOrderMerchantAndCaveats` -> `Location`

## Mentions of Order's `Items`
- **Handler**
    - [x] `SetOrderTrialDays`
    - [x] `GetOrder`
    - [x] `DeleteOrderCreds`
        - Depends on the service `DeleteOrderCreds` method.
    - [x] `CreateOrderCreds`
        - Depends on the service `CreateOrderItemCredentials` method.
    - [x] `GetOrderCreds`
        - This endpoint will remain in legacy mode assuming an order has only one item. Newer versions of the SDK should and will use `GetOrderCredsByID`.
    - [x] `GetOrderCredsByID`
        - This endpoint works on per-item basis.
- **Service**
    - [x] `SetOrderTrialDays`
    - [x] `GetOrder`
    - [x] `TransformStripeOrder`
    - [x] `ValidateOrderMerchantAndCaveats`
    - [x] `IsOrderPaid`
    - [x] `verifyDeveloperNotification`
    - [x] `verifyIOSNotification`
    - [x] `CreateAnonCardTransaction`
    - [x] `UpdateOrderStatus`
    - [x] `DeleteOrderCreds`
    - [x] `CreateOrderItemCredentials`
    - [x] `GetTimeLimitedCreds`
        - As per #2183, the method works on per-item basis, and therefore is ready.
    - [x] `GetCredentials`
        - Similar to the handler, this method is considered legacy and will remain unaware of multi-item orders.
    - [x] `GetItemCredentials`
        - As per #2183, the method works on per-item basis, and therefore is ready.
- **Datastore**
    - [x] `SetOrderTrialDays`
    - [x] `GetOrder`
    - [x] `CreateOrder`
    - [x] `GetOrderByExternalID`

## Other
- [x] Order creation requires the same credential type.
- [x] Valid for computation requires one order item.

**Comment by pavelbrm** [comment]
Updated with the ticket with a more comprehensive list of places directly or indirectly concerning the question. Will be tracking progress here. Half of the listed items require just confirming things are going to work well due to merely mentioning items. Other places though need more attention.

**Comment by husobee** [comment]
mid next week will be pairing with @pavelbrm to make sure the skus sdk is unaffected by modifications

**Comment by pavelbrm** [comment]
Got to the bottom of the list. The solution is to update the SDK to work on a per-item basis using `GetOrderCredsByID` instead of `GetOrderCreds`.

If at some point it proves necessary to support multi-item mode in the now legacy `GetOrderCreds`, then we can consider possible changes to it.
