### ISSUE TITLE
Improve how secret files are encrypted and stored in vault

### ISSUE THREAD

**Issue by kdenhartog** [brave-intl/bat-go#2203]
Right now, we're pulling the zebpay signing key secret from the config.json and [loading it as an environment variable](https://github.com/brave-intl/bat-go/blob/nitro-payments-dev/services/payments/secrets.go#L167). This is a bit confusing since PEM encoded keys would normally just be a file and then we'd not have to worry about the new line characters in the string. Can we update this so that we just upload an encrypted copy to the S3 bucket alongside the config.json file and the image pulls it and places that on the filesystem of the container?

**Comment by husobee** [comment]
not yet required for merge, but would be better to have the pem as a file.

**Comment by evq** [comment]
splitting into https://github.com/brave-intl/bat-go/issues/2295

**Comment by Sneagan** [comment]
Superseded by #2088
