### ISSUE TITLE
Allow Worker and Tooling to Use Different Enclave Addresses

### ISSUE THREAD

**Issue by Sneagan** [brave-intl/bat-go#2209]
The ALB is rewriting the `date` header we need for signature validation. To avoid this, the worker is now using an internal address to access the enclave. However, the local tooling can't use this address and needs to use the ALB address. Right now, these two share a single configuration. If the ALB can't be stopped from modifying this header, we need to separate this configuration for the tooling and worker.

**Comment by Sneagan** [comment]
The right way to do this is probably to allow passing a URL to the CLI to override the config.

**Comment by evq** [comment]
To update here, we're going to handle the other way around. We'll have the worker get the URI via env var.
