### ISSUE TITLE
Remove unused state machines

### ISSUE THREAD

**Issue by kdenhartog** [brave-intl/bat-go#2381]
https://github.com/brave-intl/bat-go/pull/1691#discussion_r1494179820
https://github.com/brave-intl/bat-go/pull/1691#discussion_r1494180075
https://github.com/brave-intl/bat-go/pull/1691#discussion_r1494160407
https://github.com/brave-intl/bat-go/pull/1691#discussion_r1494196522
https://github.com/brave-intl/bat-go/pull/1691#discussion_r1494196854
https://github.com/brave-intl/bat-go/pull/1691#discussion_r1494197039
https://github.com/brave-intl/bat-go/pull/1691#discussion_r1494198396
https://github.com/brave-intl/bat-go/pull/1691#discussion_r1494198953

**Comment by Sneagan** [comment]
Make a branch for these old machines and link it here. Then remove them from the service and PR them separately.
