### ISSUE TITLE
zebpay client library should have idempotence testing since it's not handled by the custodian

### ISSUE THREAD

**Issue by kdenhartog** [brave-intl/bat-go#2387]
https://github.com/brave-intl/bat-go/pull/1691#discussion_r1494022602

**Comment by Sneagan** [comment]
Conversation with Zebpay indicated idempotency is assured by their API.

> For idempotency, each txn is fully idempotent. If same txn is provided twice in a single request body, then the whole request will be rejected. If same txn is provided in multiple requests, then 1st request will be processed, and the next onwards it will be rejected. (Any request that contains a duplicate txn id in the body will be rejected completely. )
