### ISSUE TITLE
Fix Uphold cert issue permanently

### ISSUE THREAD

**Issue by clD11** [brave-intl/bat-go#2394]

**Comment by evq** [comment]
I think we talked about this in Slack - but we should be sure that the pinning logic is still used for both the legacy payout tooling as well as the nitro enclave based tooling.

**Comment by Miyayes** [comment]
From @evq:

>remove uphold cert pinning within the grant server since it no longer makes bat transfers
>retain pinning within the settlement tooling

Thread: https://bravesoftware.slack.com/archives/C0NPFB6H5/p1716997557234039?thread_ts=1716987389.565629&cid=C0NPFB6H5

Plan was approved by @kdenhartog: https://bravesoftware.slack.com/archives/C0NPFB6H5/p1716997743706179?thread_ts=1716987389.565629&cid=C0NPFB6H5
