### ISSUE TITLE
Local Development and Testing Environment

### ISSUE THREAD

**Issue by Sneagan** [brave-intl/bat-go#2554]
Create a fully local environment for the Payment Service including a [Worker](https://github.com/brave-intl/bat-go/blob/nitro-payments-dev/services/payments/worker.go), [Service](https://github.com/brave-intl/bat-go/blob/nitro-payments-dev/services/payments/controllers.go), Redis, QLDB, and a way to interact with it using the [Tooling](https://github.com/brave-intl/bat-go/tree/nitro-payments-dev/tools/payments).

**Comment by ibukanov** [comment]
The current status: I am prototyping Docker compose setup to run the payment components in local docker containers, https://github.com/brave-intl/bat-go/pull/2572 . The current stumbling block is access to QLDB from the container.

**Comment by ibukanov** [comment]
The current status: The payment server under testing uses QLDB test ledge and reads secretes from an undecrypted local file. The server starts without errors and serves on localhost. The worker also starts, but reports a redis error. I will focus on fixing those.

**Comment by ibukanov** [comment]
Status: both service and worker start under docker compose,  working on making ipython shell to connect to the test setup.

**Comment by ibukanov** [comment]
Status: working on integrating ipython shell and making sure that important shell commands works against the payment service and the worker running in a local container.

**Comment by ibukanov** [comment]
Status: as agreed I am working on making vault creation, bootstrap and authorize commands working in local environment. The latest changes supports the vault create/verify and initial support for bootstrap.

As there is no way to simulate nitro-KMS integration, the bootstrap and secretes loading will skip encryption with KMS key. But the rest will be supported including encrypting the config with operator keys.

**Comment by Sneagan** [comment]
The code has been moved to a new repo, so some changes are needed to get this over the line in the new repo.

**Comment by ibukanov** [comment]
The current status: the branch is moved to the payments-service repo, see https://github.com/brave-intl/payments-service/tree/igor/2554/payment-dev-env

The localenv allows to use all tools command as with nitro enclave. The difference is that the executable is run directly in the docker container and KMS is bypassed so uploaded operator shares are not encrypted with KMS key. In addition there is no Nitro attestation signing, the signature is emulated with sha256 hash.

**Comment by Sneagan** [comment]
Blocked on @Sneagan getting https://github.com/brave-intl/payments-service/pull/26/files over the line.
