### ISSUE TITLE
remove payments service from this repo

### ISSUE THREAD

**Issue by kdenhartog** [brave-intl/bat-go#2708]
The payments service has been migrated to a [separate repository](https://github.com/brave-intl/payments-service). I think that means we can now remove it from this repository and clean up or migrate issues over to that repository if they're related to payment service changes.

**Comment by clD11** [comment]
Just to confirm does this includes all payment related code including nitro:

Nitro

* libs/nitro https://github.com/brave-intl/bat-go/tree/master/libs/nitro
* service/nitro https://github.com/brave-intl/bat-go/blob/master/services/nitro/nitro.go

Payments
* services/payments: https://github.com/brave-intl/bat-go/tree/master/services/payments
* tools/payments: https://github.com/brave-intl/bat-go/tree/master/tools/payments

**Comment by clD11** [comment]
Got confirmation its okay to remove all of the above https://github.com/brave-intl/bat-go/issues/2708#issuecomment-2538477092

cc @DJAndries
