### ISSUE TITLE
Review panic recovery middleware

### ISSUE THREAD

**Issue by evq** [brave-intl/bat-go#341]
https://github.com/brave-intl/bat-go/blob/6e418097342ec694e6b3832cad13b7fff565a8d2/bin/grant-server/main.go#L76

I believe this comment is no longer accurate. It also seems we have two different middleware that are attempting to recover panics ( our internal RequestLogger and chiware Recoverer ). Can we eliminate one of these?

**Comment by husobee** [comment]
This was completed in #385 as RequestLogger now handles all recovery.
