### ISSUE TITLE
ioutil.ReadAll shouldn't be used

### ISSUE THREAD

**Issue by bbondy** [brave-intl/bat-go#38]
This is @riastradh-brave's find for `brave/go-update`, but I noticed that bat-go also uses `ioutil.ReadAll`
https://github.com/brave/go-update/pull/1#discussion_r208788854

**Comment by bbondy** [comment]
Might not cause any problems here, but worth a check.

**Comment by bbondy** [comment]
I used:

```
	limit := int64(1024 * 1024 * 10) // 10MiB
	body, err := ioutil.ReadAll(io.LimitReader(r.Body, limit))
```

**Comment by bbondy** [comment]
https://github.com/brave/go-update/pull/1/commits/0058994c05e27af356547505b6aea2c04b8b1b7e

**Comment by evq** [comment]
Looks like a possible DoS vector, this service isn't intended to be public facing however it would be good to address :+1:

**Comment by riastradh-brave** [comment]
Concur with @evq.  We should add a couple notes about denial of service.  The two attack surfaces in grant-server that I see, based on the security model written up at https://github.com/brave/internal/blob/master/security-models/bat-go/grant-server.md, are:

- HTTP requests from ledger server to grant server, which are limited by Amazon firewall policy to come from the ledger server IP address; and
- HTTP responses from Uphold, which are transmitted over authenticated HTTPS, and malicious Uphold is out of scope.

It would be reasonable (but low-priority) to impose limits to thwart this DoS vector if either the firewall policy or HTTPS certificate validation fails.
