### ISSUE TITLE
V3 Wallet API Contract Testing

### ISSUE THREAD

**Issue by husobee** [brave-intl/bat-go#463]
There exists a need to prove that a change in bat-go services has no impact to consumers of said services as a gating factor in CI.

It is proposed here that we implement contract testing of all new service APIs dynamically, starting with the V3 Wallet APIs.

1. Implement response structure schema from V3 Wallet APIs (outputs.go) as JSON Schema.
2. Store all service schema generated from step 1 in bat-go `bat-go/<service>/schemas/json/<output type>.schema`
3. Create the following tests per service, and record output of the tests `/tmp/outputs/<service>/<route-name>/<method>/<response code>.json`:
  1. Success Case
  2. All Known Status Code Failure Cases 
4. For each test case per service, perform JSON Schema Validation on the responses compared to what the schema from step 2 claims is correct.
5. If there is a failure, stop CI, and fail test.

This can be implemented as a helper library within bat-go using something like `gojsonschema` package for example or externally to the code with `jsonschema` python library as another example.

Example of using gojsonschema to validate below: 
```go
    schemaLoader := gojsonschema.NewReferenceLoader("file:///home/me/schema.json")
    documentLoader := gojsonschema.NewReferenceLoader("file:///home/me/document.json")

    result, err := gojsonschema.Validate(schemaLoader, documentLoader)
    if err != nil {
        panic(err.Error())
    }

    if result.Valid() {
        fmt.Printf("The document is valid\n")
    } else {
        fmt.Printf("The document is not valid. see errors :\n")
        for _, desc := range result.Errors() {
            fmt.Printf("- %s\n", desc)
        }
    }
```

It is suggested that json schema be developed for every input/output (and used as "validatable" interface for inputs) during the API design phase of project creation.

**Comment by evq** [comment]
@husobee have you taken a look at https://github.com/alecthomas/jsonschema? i wonder if it would be helpful for generating JSON schemas based on our existing response structs

**Comment by husobee** [comment]
I like this idea, but I would prefer to use this in a bat-go "command" like `./bat-go generate json-schema` 

If we ran that during CI process every time and compared the diff of the json-schema with the existing json-schema generated from prior runs we would be able to notice changes to the schema, and by inference, the response structure as well.
