### ISSUE TITLE
Circuit tripping alerting changes

### ISSUE THREAD

**Issue by jsecretan** [brave-intl/bat-go#54]
To clarify when grants are unavailable when a "circuit" has been tripped, we want to generate an explicit Sentry error specifying the circuit tripping.

We should then change our alerting in our monitoring slack channels to look only for this specific event.

Finally, we should expose an endpoint that can be monitored by DevOps to confirm when this has been tripped, as this is a critical service. (DevOps follow up to this is in https://github.com/brave/devops/issues/535).

**Comment by evq** [comment]
Sentry has been updated to look for the `breaker: true` or `out-of-funds: true` which will be added in https://github.com/brave-intl/bat-go/pull/55
