### ISSUE TITLE
Automatically unlink the oldest wallet when a user tries to exceed the limit

### ISSUE THREAD

**Issue by fmarier** [brave-intl/bat-go#730]
While we are also adding a [support API to manually change wallet linking](https://github.com/brave-intl/bat-go/issues/709), we should try to address one of the most common cases when users run into the wallet linking limit:

1. User links 4 devices over time (Pixel 2, Laptop, Desktop, Pixel 3) to their Uphold account.
2. User buys a new phone (Pixel 4a) and authenticating using the Uphold OAuth flow.
3. Client tries to link the new device with the Grants service, but since the linking limit has already been reached, this operation can't proceed directly.
5. Grants service looks through all existing linked wallets and finds that the Pixel 2 is the one which has gone the longest without receiving a payment from Brave (presumably the user has lost/replaced that old phone).
6. Grants service checks that the Pixel 2 has been linked more than 14 days ago.
7. Grants service unlinks the Pixel 2, then links the Pixel 4a.

If the user tries to link yet another device, then we go through the same process. If all of the linked devices have been linked in the last 14 days, then an error message is shown telling the user that:
- there is a limit of 4 linked devices per account
- try again in 2 weeks

**Comment by fmarier** [comment]
Also, to gracefully handle the case the device that gets unlinked is still in use, we do need to address the infamous"semi verified" state where the browser is verified with uphold but the linking no longer exists on our servers.

**Comment by spitrip82** [comment]
I no longer have access to my old devices how can I solve this problem and verified my wallet ? i still need to whait 2 weeks ? 
Sorry for the question but as I don't speak English very well, I didn't understand your post. Thank you in advance for your help
![Captura de ecrã 2022-02-09 004815 brave](https://user-images.githubusercontent.com/76714275/153101878-5b1bf1ca-9e7e-4cd9-a599-a11265753d47.png)

**Comment by fmarier** [comment]
The work described in this issue has not been implemented. It was just a proposal/idea.

We are actually working on a different solution that will remove the need for a waiting period.
