### ISSUE TITLE
update repo from recent ledger changes

### ISSUE THREAD

**Issue by maikelmclauflin** [brave-intl/bat-go#80]
## features
- [x] fastly token check
  - validate in grants get and put
- [ ] cohorts = control,grant,test,ads
- [ ] wallet cooldown w/ bypass
- [x] get list of allowed ads countries from ads server, do xor for `ads` grants vs others

### modify
- [ ] `GET /v3/grants` 
  - always respond 404 after android check
- [ ] `GET /v4/grants`
  - ads android
- [ ] `GET /v5/grants`
  - ugp ads
  - android hacks
### add
- [ ] `POST /v2/wallet/{paymentId}/claim`
  - use create and commit tx
- [ ] `GET /v2/wallet/{paymentId}/grants/{type}`
  - composite grants
  - promotion id exclusions
### remove
- [ ] `GET /v1/owners/{owner}/wallet`
- [ ] `POST /v3/owners/{owner}/wallet/card`
- [ ] `PUT /v1/owners/{owner}/wallet`
- [ ] `PATCH /v1/owners/{owner}/wallet`

## instrumentation
- [ ] funds_received_count
- [ ] votes_issued_counter
- [ ] viewRefresh_request_buckets_milliseconds
- [ ] anonizeRegister_request_buckets_milliseconds
- [ ] anonizeVerify_request_buckets_milliseconds
- [ ] uphold_request_buckets_milliseconds

**Comment by evq** [comment]
I think everything on this has been broken out into issues
