### ISSUE TITLE
Support tool: userdrain retry

### ISSUE THREAD

**Issue by Miyayes** [brave-intl/bat-go#961]
## Description 

Support tool: userdrain retry.

**Comment by husobee** [comment]
[userdrain-retry.pdf](https://github.com/brave-intl/bat-go/files/7475509/userdrain-retry.pdf)

**Comment by husobee** [comment]
[userdrain-retry-1.pdf](https://github.com/brave-intl/bat-go/files/7475521/userdrain-retry-1.pdf)
